---
- block:
    - name: Update apt cache
      apt:
        update_cache: true
      register: _pre_update_apt_cache
      until: _pre_update_apt_cache is succeeded
      when:
        - ansible_pkg_mgr == "apt"
    - name: Install dependencies
      package:
        name: "{{ rspamd_dependencies }}"
        state: present
      register: _install_dep_packages
      until: _install_dep_packages is succeeded
      retries: 5
      delay: 2
- block:
    - name: Import rspamd GPG signing key [Debian/Ubuntu]
      apt_key:
        url: "https://rspamd.com/apt-stable/gpg.key"
        state: present
      register: _add_apt_key
      until: _add_apt_key is succeeded
      retries: 5
      delay: 2

    - name: Add rspamd repository [Debian/Ubuntu]
      apt_repository:
        repo: "deb http://rspamd.com/apt-stable {{ ansible_distribution_release }} main"
        state: present
        update_cache: true
      register: _update_apt_cache
      until: _update_apt_cache is succeeded
      retries: 5
      delay: 2
  when:
    - ansible_pkg_mgr == "apt"

- name: Install rspamd
  package:
    name: "{{ rspamd_packages }}"
  register: _install_packages
  until: _install_packages is succeeded
  retries: 5
  delay: 2
  notify: restart rspamd
- import_tasks: configure.yml
